[versions]
appcompat = "1.6.1"
constraintlayout = "2.1.4"
coreKtx = "1.12.0"
espressoCore = "3.5.1"
hiltAndroidCompiler = "2.48.1"
junit = "4.13.2"
junitVersion = "1.1.5"
material = "1.10.0"
okhttp = "4.10.0"
androidGradlePlugin = "8.1.2"

appDynamics = "23.7.1"

[libraries]
appDynamics-runtime = { group = "com.appdynamics", name = "appdynamics-runtime", version.ref = "appDynamics" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }


[plugins]
appdynamics = { id = "adeum", version.ref = "appDynamics" }